taplo-ide/schemas/pyproject.json

Sorry about the noise from #44, I decided to leave out any changes to pyproject.yaml here - you can port these changes to that file if you'd like.
Resolves #35, This also (re-)addresses some of the concerns from #34.

Update pyproject.json with custom version

---

taplo/Cargo.toml

Good afternoon, we would like to use taplo and some components from taplo's LSP to provide autocompletion for toml configuration in our linter's LSP. However, taplo uses a relatively old version of lsp-types which is incompatible with tower-lsp. This PR bumps the version of lsp-types to match tower-lsp

Bump lsp-types version to match tower-lsp

---

taplo/CHANGELOG.md
taplo/schemas/rustfmt.json
taplo/src/schema.rs

This adds a schema for `rustfmt.toml` and `.rustfmt.toml` files.
The schema is auto-generated with a script I wrote: https://github.com/Aloso/rustfmt-schema-maker
I hope the code is okay, because I was too lazy to locally build the extension 😝

Add builtin rustfmt schema

---

taplo/Cargo.toml

Hey 👋 
I recently released assert-json-diff 2.0.0 which had [a few breaking changes](https://github.com/davidpdrsn/assert-json-diff/blob/main/CHANGELOG.md#200---2021-01-23).

Update assert-json-diff to 2.0

---

schemas/rustfmt.toml.json

This commit adds unstable options to the `rustfmt` schema.
Again, this file is auto-generated with [rustfmt-schema-maker](https://github.com/Aloso/rustfmt-schema-maker).
Unfortunately the order of the keys changed because the tool uses a `HashMap`, so the git diff is rather noisy. I'll change it to a `BTreeMap` next time.

Include unstable rustfmt options

---

taplo/Cargo.toml
taplo/src/lib.rs

Hello! Thanks for this crate! I've been investigating a bunch of TOML parsers and found yours to be the best out of all the ones I tried. I'd like to use the parser in a Wasm build, but right now the crate adds wasm-bindgen exports, which isn't desirable when it's used internally by some other Wasm code.
After this change, the code should work the same as it currently does. I think though that eventually it should be flipped so that using wasm-bindgen is opt-in rather than opt-out.
Thanks! (Also, I've used the parser to create a code formatter... I understand that taplo has a built-in code formatter, but toml is such a simple language and I prefer full control over the output)

Move wasm-bindgen usage to a cargo feature to support building for Wasm without defining exports

---

taplo/Cargo.toml
taplo/src/dom/mod.rs
taplo/src/formatter/mod.rs
taplo/src/parser/mod.rs
taplo/src/tests/formatter.rs

PR for #123.
Notable changes include:
- we work with strings only (also removed SmolStr)
- better handling of comments with a generic trait
- simplified code where possible
TODO:

Formatter Rework

---

taplo-lsp/bin/lsp/stdio.rs
taplo-lsp/bin/lsp/tcp.rs

fixes #162
I think that the vscode extension uses wasm binding, so it should not be affected by this fix.

fix unneeded content-length adjustment

---

schemas/makefile.toml.json

I put together a schema for cargo-make makefiles.
It works fine with the taplo CLI validation, but there's some quirkiness in the vscode extension, mostly with tooltips for items, where it seems to be pulling every subschema description from `oneOf`/`anyOf` schema declarations into the parent schema, and then...making them bold and larger for some reason? Anyway, that appears to be a bug on the vscode extension side, not the schema itself afaik. It might be a good test case for it.
Screenshot of the issue:

cargo-make Makefile.toml schema

---

.github/workflows/ci.yaml

Some of the vim users want a binary of taplo-lsp to use it without installing rust. 
This GHA creates a draft release since we need to avoid conflicts when it makes the binaries for multiple OS.
https://github.com/tamasfe/taplo/issues/90
https://github.com/kkiyama117/taplo-gh-test
https://github.com/kkiyama117/taplo-gh-test/releases/tag/release-cli-0.4.3

Add CLI release workflows

---

site/src/pages/configuration.mdx

If I need to create an issue to fix the document, I am sorry.
After reading [CONTRIBUTING.md](https://github.com/tamasfe/taplo/blob/master/CONTRIBUTING.md), I don't think I need to create an issue to fix the document. So, I did not create the issue.
---
If it is `keys = "dependencies"` as in the following, an error will occur, so I fixed it to `keys = ["dependencies"]`.
```toml
[formatting]
reorder_keys = false
[[rule]]
include = ["**/Cargo.toml"]
keys = "dependencies"
[rule.formatting]
reorder_keys = true
```
```shell
> taplo format
error: failed to read configuration: invalid type: string "dependencies", expected a sequence for key `rule.keys` at line 6 column 8
```

docs(site): fix keys value syntax to array in config file

---

taplo-lsp/Cargo.toml
taplo-lsp/src/handlers.rs
taplo-lsp/src/handlers/code_action.rs
taplo-lsp/src/handlers/completion.rs

Sometimes Emacs lsp-mode sends a request containing a position parameter before synchronizing with `DidChangeTextDocument`.
At that time, the `mapper` may not be able to find the stored position and panicked with `unwrap`.
This fix is to return `Ok(None)` instead of `unwrap` to avoid this case.
Perhaps this may fix the problem like a https://github.com/golang/go/issues/48249 as well.
This PR includes commit of https://github.com/tamasfe/taplo/pull/184.

Avoid panic if request position is out of mapper's range

---

lsp-async-stub/Cargo.toml
lsp-async-stub/src/handler.rs
lsp-async-stub/src/lib.rs
lsp-async-stub/src/listen.rs
lsp-async-stub/src/listen/stdio.rs
lsp-async-stub/src/listen/tcp.rs
taplo-lsp/Cargo.toml
taplo-lsp/bin/lsp/stdio.rs
taplo-lsp/bin/lsp/tcp.rs
taplo-lsp/src/external/native/mod.rs
taplo-lsp/src/external/wasm32/mod.rs

fixes #187
use `tokio::task::spawn_local` and remove `Send` requirements.
Note:
The use of multi-threaded executor is still exists in the following places:
- `create_input`
- `create_output`
- `taplo-cli`

Make it possible to use !Send even in Native LSP

---

site/static/schemas/rustfmt.toml.json

Rust 1.56 (current stable, at the time of this writing) has introduced [Rust Edition 2021](https://doc.rust-lang.org/edition-guide/rust-2021/index.html). This commit updates the list to prevent erroneously showing an error in a Cargo.toml that uses it.

Update rust edition list to include 2021

---

js/vscode/src/syntax/composite/entry.ts
js/vscode/toml.tmLanguage.json

This should provide a much better experience when syntax highlighting in vscode. Most(but not all) themes treat `variable.key` and `variable.key.table` the same(no highlighting for either), which makes for an inconsistent and poorly supported syntax highlighting experience. As mentioned in #143 is what the json grammar uses as well.

Swaps over from `variable.key.toml` to `support.type.property-name.toml` in vscode grammar

---

schemas/rustfmt.toml.json

Add support for Rustfmt configuration file with a leading dot `.rustfmt.toml`, in addition to one without `rustfmt.toml`.

Add support  for `.rustfmt.toml`

---

schemas/rust-toolchain.toml.json

First part of #228.
I am hoping to get to `.cargo/config.toml` next, but it has _lots_ of fields so may take a bit longer.
Please let me know if there's anything you'd like added or changed, I think I got most of the docs (pulled from [the rustup book](https://rust-lang.github.io/rustup/index.html)), but may have overlooked or typoed something.

Add initial `rust-toolchain.toml` schema

---

schemas/fly.toml.json

This PR aims to get VSCode schema validation for the [Fly.io](https://fly.io) deployment configuration file, [fly.toml](https://fly.io/docs/reference/configuration).

Add a schema for Fly.io's fly.toml

---

crates/taplo-cli/src/args.rs
crates/taplo-cli/src/commands/format.rs

This PR introduces the `--stdin-filepath` option to the `format` command.
This was inspired by ESLint's `--stdin-filename` and Prettier's [`--stdin-filepath`](https://prettier.io/docs/en/cli.html#--stdin-filepath). It doesn't have any behavior in the actual parsing of files or their resolution.
It is mainly useful when showing error information. In such cases, instead of getting:
```txt
┌─ -:2:5
│
2 │ [bar=6
│     ^ expected "]"
```
One would get:
```txt
┌─ ./foo.toml:2:5
│
2 │ [bar=6
│     ^ expected "]"
```
By executing `format` as `taplo format --stdin-filepath ./foo.toml -`.

Add `--stdin-filepath` option to format cmd

---

editors/vscode/README.md

This only affected the vscode readme. Image files were placed in the `images` sub-directory for the vscode directory, but its corresponding `README.md` was not updated with the new paths.

Fix broken image links due to a previous file reorganization

---

crates/taplo-cli/Cargo.toml
crates/taplo-common/Cargo.toml
crates/taplo-lsp/Cargo.toml

Removes the dependency on openssl by using the `rustls-tls` feature flags across all toplo packages.

drop the openssl dependency

---

Cargo.toml
crates/lsp-async-stub/Cargo.toml
crates/taplo-cli/Cargo.toml
crates/taplo-cli/src/args.rs
crates/taplo-cli/src/commands/format.rs
crates/taplo-common/Cargo.toml
crates/taplo-wasm/Cargo.toml
taplo.toml

It's not uncommon to use a formatter in CI where a subset of contributors do not have the tool installed. That set of contributors is usually very appreciative of direct cues what to fix.
The changes:
Adds a dependency to `prettydiff` and `ansi_term` for creating the diff and coloring, there is currently (almost) no clustering of diff lines, this is to be improved.

add delta view to taplo-cli

---

crates/taplo-cli/build.rs

This env's use was removed in #211, so the build script is unnecessary.

fix(cli): remove build script

---

crates/taplo/src/formatter/mod.rs
crates/taplo/src/tests/formatter.rs
editors/vscode/package.json
site/site/configuration/formatter-options.md

A fix for #338 and #158 issues.

feat: reorder_arrays flag

---

crates/lsp-async-stub/src/listen.rs

These lines in the Server loop discard any messages with the shutdown method. The Server can handle and correctly respond to shutdown requests, though, so there's no need to discard the message.

Handle LSP shutdown request

---

site/site/cli/installation/binary.md

Adjust the broken download links for the cli binaries so that they work with the latest tag.
Signed-off-by: Nico Braun <rainbowstack@gmail.com>
fix: #365

docs(cli): fix binary download links

---

crates/taplo/src/formatter/mod.rs
crates/taplo/src/tests/formatter.rs

Fixes #404 by adding a new option (as to not disrupt existing behavior) that controls whether single comments get aligned.

Add `align_single_comments` option

---

site/site/cli/installation/binary.md

Updates docs to include links for Windows builds and more architectures added in #330

docs: add windows builds and more architectures

---

crates/taplo-common/src/config.rs
crates/taplo-lsp/src/handlers/formatting.rs

Previously, using a configuration like:
```taplo.toml
[formatting]
reorder_keys = false
align_entries = true
[[rule]]
include = ["**/taplo.toml", "**/.taplo.toml"]
[rule.formatting]
reorder_keys = true
```
Running `taplo fmt` would  sort the two formatting keys, but the language server (i.e. "format document" in vscode) would not.
The trouble is that the language server was comparing an include rule (prefixed with the absolute path of a workspace) against a file URI directly, and a GlobRule that's including
`/absolute/path/**/taplo.toml` does not match a normalized URI string like `file:///absolute/path/taplo.toml`.
Also, because of the path prefix, changing the config file to
```
include = ["file://**/taplo.toml"]
```
produces a similar result (neither `taplo fmt` nor the server apply …

fix: language server include rule matching

---

crates/taplo-cli/src/commands/format.rs

Use a single stdout object to avoid interleaving

---

crates/taplo-cli/Cargo.toml
crates/taplo-cli/src/args.rs
crates/taplo-cli/src/lib.rs
site/site/cli/usage/configuration.md

This pull request improves the configuration file lookup logic in taplo-cli. The changes enable the CLI to search for a configuration file in the `TAPLO_CONFIG` environment variable if no configuration file is found in the current working directory and no explicit path has been provided by the user.
Changes:
1. Added support for TAPLO_CONFIG in the `load_config` function.
2. Minor documentation updates

taplo-cli: add ENV variable support

---

crates/taplo-lsp/src/handlers/hover.rs

If a `title` is given to `jsonschema` without `description`, the content on hover will be empty.
For example, this ocurre for the `project` key in `pyproject.toml`.

taplo-lsp: fix hover content.

---

.vscode/launch.json
Cargo.lock
crates/taplo-common/Cargo.toml
crates/taplo-wasm/Cargo.lock
crates/taplo-wasm/Cargo.toml
crates/taplo/Cargo.toml
editors/vscode/src/server.ts

As mentioned in https://github.com/tamasfe/taplo/issues/434#issuecomment-1675993012, `getrandom` has a workaround built in around the fact that node.js’s ESM story is still not properly solved (https://github.com/rust-random/getrandom/issues/256#issuecomment-1158600778)
That workaround exists in getrandom 0.2.8+, but several crates still accepted ahash 0.7.6, which kept the getrandom version at 0.2.7.
This PR bumps the ahash versions we depend on so compatible getrandom versions can be used.
Fixes #434

Fix VS Code LSP crash

---

crates/taplo/src/formatter/mod.rs
crates/taplo/src/tests/formatter.rs

Fix comments with brackets

---

crates/taplo-cli/src/lib.rs
crates/taplo-common/src/util.rs
crates/taplo-lsp/src/world.rs
site/site/configuration/using-schemas.md

Resolve #443 
Inspired by [Node.js setting](https://nodejs.org/api/cli.html#node_extra_ca_certsfile), I named the env var to be `TAPLO_EXTRA_CA_CERTS` (plural here because one file could contain many certs).
I extracted the getting `reqwest` client part as a function though I don't know exactly where the best location for this function is. I temporarily put it in `taplo-common/util.rs`.
I tested the build on my local environment described in the issue and it worked perfectly.
to: @ia0 
How should we document this?
I was thinking about making the error more obvious and adding a suggestion to let the user know they need to add the environment variable. Though I don't really know how to match the `UnknownIssuer` error from `reqwest`.

Support adding custom CA

---

Cargo.lock
crates/taplo-wasm/Cargo.lock
util/test-gen/Cargo.lock

See https://github.com/rust-lang/rust/issues/113152 for more details.
This commit was generated by:
```
find . -name Cargo.toml -execdir cargo update -p proc-macro2 \;
```

Update proc-macro2 to fix compilation error with nightly

---

site/site/cli/installation/npm.md

NPM and Yarn already had commands listed, this just shortens the document and adds commands for installing with pnpm.

Add pnpm install methods to npm docs

---

editors/vscode/package.json

For some reason you have to make links in settings descriptions with markdown syntax for them to turn into clickable links.
*The link in the bottom right, which uses the bracket parenthesis syntax (`[123](https://example.com)`), is underlined and clickable while the plain link at the top center is not converted into a link and has to copy pasted.*
I just took the title of the docs page and the section heading as the link text.

chore: make link in settings description clickable

---

crates/lsp-async-stub/src/listen.rs
crates/taplo-cli/src/args.rs
crates/taplo-cli/src/commands/lint.rs
crates/taplo-cli/src/commands/queries.rs
crates/taplo-common/src/schema/cache.rs
crates/taplo/src/formatter/mod.rs
crates/taplo/src/parser/mod.rs
crates/taplo/src/tests/formatter.rs

Added `--separator <str>` flag for `taplo get`.
From the helpdoc:
```
--separator <SEPARATOR>
A string that separates array values when printing to stdout.
If `--separator` is specified with a non text output format, the operation will fail.
```

Add option to specify separator for text output

---

.github/workflows/releases.yaml
docker/cli-alpine.Dockerfile
docker/cli-full-alpine.Dockerfile

* Add `linux/arm64` in the build platforms
* Use a matrix for parallel build of Docker images
* Update parent images to `rust:1.73-alpine3.18 as build` and `alpine:3.18`

ci: build docker images for linux/arm64

---

crates/taplo/src/formatter/mod.rs

Fixes [#511](https://github.com/tamasfe/taplo/issues/511).
-----
First time contributing to an open-source project, so please let me know if I've done anything wrong or how I can improve. Also should I squash my commits before submitting the PR?
And running cargo fmt completely changes the way the imports are structured, so I ended up saving without formatting, but I'm not sure if that's what's intended

Sort by crate lexicographical order

---

Cargo.lock
crates/taplo-cli/Cargo.toml

(Context: Sniffing out different sources of old `clap` versions that are still getting downloaded)
`prettydiff` is one of those crates that also doubles as a CLI binary with a default `cli` feature for all the CLI bits. This is their only default feature and it pulls in `structopt` (which uses old clap v2.0) and `prettytable-rs`

Toggle off default `clap` dependency for `prettydiff`

---

.github/workflows/releases.yaml

Fixes: #542 
In #496 i introduced a bug in the release process by referencing a not yet defined environment variable `env.RELEASE_VERSION` in the matrix.
Causing this failure: https://github.com/tamasfe/taplo/actions/runs/7742605055/workflow#L268
This can be fixed by extracting the version fetching steps in its own `get_version` job and make jobs that require it to depend on it. Then instead of referencing an environment variable we use the `get_version` job outputs.
I also added the `workflow_dispatch` trigger to allow running the release workflow manually. So that it should be possible to re-run it to fix the releases, using the desired tag as the git ref:
I've created a dummy repository to test the workflow logic (by fetching and echoing the versions) and it works fine: …

ci(releases): fetch tools versions in its own job

---

Cargo.lock

This fixes build with musl libc.

chore(deps): bump getrandom from 0.2.8 to 0.2.12

---

crates/taplo/src/formatter/mod.rs
site/site/configuration/formatter-options.md

Addresses part of #390.
The `array_auto_expand` formatter configuration option will prefer to leave arrays on a single line until they exceed the configured column length. The documentation didn't make this caveat clear, and lead some users to expect that all arrays would be expanded regardless.
This does not modify behavior at all, just documents it.

Clarify that array_auto_expand is conditional

---

crates/taplo/src/dom/node.rs
crates/taplo/src/tests/formatter.rs

Fixes #464
When using taplo rules to limit configuration to specific portions of a document, trailing comments would break formatting.
`Node#text_ranges`, when considering tables, was returning ranges for each interior element and the table header, which excluded trailing comments. When the formatter walks the code and is trying to determine which rules apply to a table, it checks whether the table is a subset of the rule "span". When there is a trailing comment, this check fails, and the rule will never apply.
Since the dom `Node` for tables contains only a reference to the table header, we can get the text range of the entire table, including trailing or interior comments, by traversing up to the parent and taking its text range. If this is unavailable, the previous behavior is used. …

Account for trailing comments in span handling

---

crates/taplo-cli/Cargo.toml
crates/taplo-common/Cargo.toml
crates/taplo-lsp/Cargo.toml
crates/taplo-wasm/Cargo.toml

This reverts 4be1d1eb9fba62ddd6cc7cf53058b6bce3d66c7c and make it more convenient to build taplo-common without explicitly providing a feature.
Fixes #553

Do not enable default-tls unconditionally

---

Cargo.lock
crates/taplo-common/CHANGELOG.md
crates/taplo-common/Cargo.toml

This will close https://github.com/tamasfe/taplo/issues/544.

chore(deps): bump dependencies to support RISC-V platform

---

crates/taplo-cli/Cargo.toml
crates/taplo-common/Cargo.toml
crates/taplo-common/src/util.rs
crates/taplo-lsp/Cargo.toml
crates/taplo-wasm/Cargo.toml

Fixes #564.
I just hid all the TLS inside a conditionally defined helper.

fix: allow building with `no-default-features`

---

crates/taplo-cli/Cargo.toml
crates/taplo-cli/src/args.rs
crates/taplo-cli/src/commands/lsp.rs

see #506 - this only supports 1 config file being passed in (the same behavior as other taplo commands) but it should do the trick for our desired case :)

add GeneralArgs support to lsp command

---

crates/lsp-async-stub/Cargo.toml
crates/taplo-common/Cargo.toml
crates/taplo-wasm/Cargo.toml

Hi! While scraping crates.io I've found some of your crates are missing the `repository` field, making it harder for users or automated tools to find the source git repository. Git PR fixes it by adding the repository field to those crates.

Add repository attribute to crates missing it

---

crates/taplo/src/formatter/mod.rs
crates/taplo/src/tests/formatter.rs

In this case, the two comments match up.
Discovered while doing https://github.com/gaborbernat/pyproject-fmt-rust

Fix realign of comment makes debug assert fail

---

crates/taplo-cli/src/printing.rs
crates/taplo-common/src/schema/mod.rs
crates/taplo-lsp/src/diagnostics.rs
crates/taplo-lsp/src/handlers/document_symbols.rs
crates/taplo-lsp/src/query.rs
crates/taplo/src/dom/node.rs
crates/taplo/src/formatter/mod.rs

At replit we use taplo for providing lsp support for our [`.replit` configuration file](https://docs.replit.com/replit-workspace/configuring-repl#replit-file) in Repls. We love Taplo!
However, when an unexpected property appears that's invalid according to `additionalProperties: false` from the corresponding JSON schema, the LSP highlights the whole file!
for example, making invalid changes to this valid `.replit` file i used for a [throwaway Repl I made when debugging this issue](https://replit.com/t/replit/onreplit/repls/japlo/view):
```toml
run = "cargo run -- /etc/replit/dotreplit.schema.json dotreplit.json"
modules = ["rust-stable"]
[nix]
channel = "stable-24_05"
```
results in this UX:
note in this screenshot that the diagnostics are collated to the first diagnostic range, which is …

improve error locations for unexpected properties

---

Cargo.lock
crates/taplo-cli/Cargo.toml
crates/taplo-common/Cargo.toml

On compilers that are Rust 1.65+, the only effect of this feature is bringing in an extra unused dependency for no reason. Taplo does not support compilers older than Rust 1.65. The oldest supported compiler currently is Rust 1.74.

Remove backtrace feature from anyhow dependency

---

crates/taplo-common/src/schema/associations.rs
editors/vscode/package.json

SchemaStore.org is in the process of transition to GitHub pages hosting. The new, and more canonical, URL for the catalog is:
> https://json.schemastore.org/api/json/catalog.json
though this does require following a redirect.
Ref: SchemaStore/schemastore#4759
Ref: SchemaStore/schemastore#4763
Ref: tamasfe/taplo#800

fix: use new schemastore catalog url
