schemas/dein.toml.json

Add schema to support [dein.nvim](https://github.com/Shougo/dein.vim) toml support.
Some mistakes may exists and some supports are incomplete (e.x: completions for vimscript) but almost all the work is done.
- Add dein.toml schema

Dein.nvim support

---

schemas/dein.toml.json

I'm sorry but I should change descriptions of schema for `dein.nvim`for better expression in official `taplo` website, and also found some mistakes in JSON-schema, so I've fixed them.

Refactor and fix dein schema

---

taplo-lsp/src/handlers.rs
taplo-lsp/src/handlers/diagnostics.rs
taplo-lsp/src/lib.rs

Fixes #118, see commit message.
I also added a bunch of comments while figuring out the logic.

feat(taplo-lsp): import #:schema-directives relative to file 

---

schemas/dein.toml.json

dein.vim has a new schema on  https://github.com/Shougo/dein.vim/commit/58b73f278e66b90bbb042ac532ba3d2c973c2731
This PR corresponds to that.

Add multiple_plugins on dein schema

---

taplo-lsp/Cargo.toml

fix lsp-async-stub version

---

taplo-cli/src/format.rs
taplo-cli/src/lib.rs

close #191 
This PR is not been communicate with project maintainers, so feel free to close or push code to this branch.
Open this PR to reduce time cost, since we are living in different time zone.

feat: add --check option to taplo-cli format command

---

schemas/dein.toml.json

I changed about these:
- Update and fix links to help file of dein.vim
- Remove deprecated properties of plugins (`on_i`, `on_idle`)
- Add new properties of plugins (`merge_ftdetect`,  `om_cmd`, `on_lua` and more)
- Some few refactoring

fix: follow latest dein.vim json schema

---

site/src/pages/lsp.mdx

Update lsp installation documentation

---

editors/vscode/language-configuration.json

Also don't auto close apostrophe in comments

Don't auto close string delimiters in strings.

---

crates/taplo-cli/src/commands/format.rs
crates/taplo-cli/src/commands/lint.rs
crates/taplo-cli/src/lib.rs
crates/taplo-common/Cargo.toml
crates/taplo-common/src/config.rs
crates/taplo-common/src/environment.rs
crates/taplo-common/src/schema/associations.rs
crates/taplo-common/src/schema/mod.rs
crates/taplo-common/src/util.rs
crates/taplo-lsp/src/handlers/formatting.rs
crates/taplo-lsp/src/world.rs

Handle percent encoding and backslashes in paths

---

.github/workflows/releases.yaml

- build taplo and taplo-full for all platforms
- add x86/aarch64
Fixes #90 
Fixes #289 
Fixes #232

feat(ci): build additional architectures

---

.github/FUNDING.yml

It's been a while since I did anything with this project, it doesn't make sense to have me in `FUNDING.yml`.

chore: remove tamasfe from funding

---

CONTRIBUTING.md
crates/taplo-cli/README.md

Just discovered this project which seem to suits my need! A couple of links broken, this commit is not exhaustive but only repair links I've clicked on while looking at the repo.

Fix doc links

---

.github/workflows/releases.yaml

ci: fix windows gzip archive

---

site/site/.vitepress/components/Editor.vue

This should fix site deploy workflow

fix(site): fix codemirror import

---

crates/taplo-common/src/schema/associations.rs

This creates conflicting rules.
Fixes #413

Do not change the extension of catalog paths

---

crates/taplo-cli/src/args.rs

Update link to formatting options shown in formatter help

---

site/site/configuration/formatter-options.md

Closes https://github.com/tamasfe/taplo/issues/375 @ia0

docs(vscode): Reload to make the format settings to take effect

---

site/site/.vitepress/config.ts
site/site/cli/installation/homebrew.md

There is a Homebrew formula (tamasfe#251) but it was never added to the docs.

Add Homebrew install to docs

---

crates/taplo/src/formatter/mod.rs

Simplify and fix table indentation logic

---

CONTRIBUTING.md

Fixes a few incorrect links (see: https://github.com/tamasfe/taplo/issues/318#issuecomment-1254873884).

docs: fix contributing.md links

---

crates/taplo-common/src/schema/associations.rs

Save index to cache as it would be returned

---

.github/workflows/releases.yaml

Add aarch64 windows builds and link runtime statically

---

.github/workflows/releases.yaml
docker-bake.hcl
docker/alpine/Dockerfile

docker: add oci-shell target for OCI images with /bin/sh requirements
